build:
    nodes:
        analysis:
            project_setup:
                override:
                    - 'true'
            tests:
                override:
                    - php-scrutinizer-run
                    -
                        command: phpcs-run
                        use_website_config: true
                    - js-scrutinizer-run
        tests: true
    environment:
        php: 7.3.0
    services:
        mariadb: 10
    project_setup:
        before:
            - cp .env.travis .env
            - php artisan key:generate
        override: []
        after: []
filter:
    paths:
        - 'app/*'
    excluded_paths:
        - 'app/views/*'
        - 'app/config/*'
        - 'app/database/*'
        - '*.min.js'
        - '*/vendor/*'
        - '*/build/*'
checks:
    php: true
    javascript: true
coding_style:
    php:
        spaces:
            around_operators:
                concatenation: true