language: php
php:
  - '7.1'
  - '7.2'
  - '7.3'
# stolen from https://stackoverflow.com/questions/38924701/how-to-setup-travis-ci-with-laravel-5-invalidargumentexception
before_script:
  - mkdir bootstrap/cache
  - mkdir storage
  - mkdir storage/app
  - mkdir storage/framework
  - mkdir storage/framework/sessions
  - mkdir storage/framework/cache
  - mkdir storage/framework/views
  - chmod 777 -R storage
  - cp .env.travis .env
  - mysql -e 'create database homestead;'
  - composer self-update
  - composer install --no-interaction
  - php artisan key:generate
  - php artisan migrate:refresh --seed

script:
  - vendor/bin/phpunit