# dist must be given in order to use a current mysql version
dist: bionic
language: php
php:
  - '7.2'
  - '7.3'
  - '7.4'
services:
  - mysql
# stolen from https://stackoverflow.com/questions/38924701/how-to-setup-travis-ci-with-laravel-5-invalidargumentexception
before_script:
  - npm install -g snyk
  - snyk auth $SNYK_TOKEN
  - chmod 777 -R storage
  - cp .env.travis .env
  - mysql -e 'create database homestead;'
  - composer self-update
  - composer install --no-interaction
  - php artisan key:generate
  - php artisan migrate:refresh --seed
  - php artisan passport:keys

script:
  # Check if all routes lead to a controller / ensure there are no typos in strings
  - php artisan route:list
  # Run phpunit test suites
  - vendor/bin/phpunit
  - rm package.json # else snyk scan will test npm and not composer
  - snyk test

after_script:
  - snyk monitor

# snyk config stolen from: https://blog.travis-ci.com/2017-04-20-continuous-security-snyk-travis-ci/