version: '2'
services:
  #app:
  #  image: kyleparisi/larasible
  #  ports:
  #    - 80:80
  #  environment:
  #    - APP_ENV=testing
  #  volumes:
  #    - ./:/var/www/default

  mysql:
    image: mysql:5.7
    ports:
      - 3306:3306
    environment:
      - MYSQL_DATABASE=homestead
      - MYSQL_USER=homestead
      - MYSQL_PASSWORD=secret
      - MYSQL_ROOT_PASSWORD=secret
    #volumes: 
      #- mysql_data:/var/lib/mysql

  myadmin:
    image: phpmyadmin/phpmyadmin:latest
    ports:
      - 8080:80
    external_links:
      - mysql:db

  # Currently not working as expected. Watch https://github.com/rnwood/smtp4dev for updates
  # Use instead 
  #smtp4dev:
  #  image: rnwood/smtp4dev:linux-amd64-v3
  #  ports:
  #    - 8081:80
  #    - "2525:25"

#volumes: 
  # mysql_data: