version: '2'
services:

  mysql:
    image: mysql:5.7
    ports:
      - 3306:3306
    environment:
      - MYSQL_DATABASE=homestead
      - MYSQL_USER=homestead
      - MYSQL_PASSWORD=secret
      - MYSQL_ROOT_PASSWORD=secret
    #volumes: 
      #- mysql_data:/var/lib/mysql

  myadmin:
    image: phpmyadmin/phpmyadmin:latest
    ports:
      - 8080:80
    external_links:
      - mysql:db

  smtp4dev:
    image: rnwood/smtp4dev:linux-amd64-v3
    ports:
      - 3000:80
      - "2525:25"

#volumes: 
  # mysql_data: